[[mgr.prepend_keymap]]
on = ["<Enter>"]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "plugin diff"
desc = "Diff the selected with hovered file"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"
desc = "Zoxide plugin"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"
desc = "Fzf plugin"


[[mgr.append_keymap]]
on = ["g", "b"]
run = "my-not-exist-cmd-script"
